import {ArrowRight, Check, ChevronsUpDown, Circle, Copy, Edit, ExternalLink, File, HelpCircle, Home, Loader2, Mail, MessageSquare, Moon, PanelLeft, Plus, PlusCircle, Search, Server, Settings, Share2, Shield, ShieldCheck, Sun, Trash, User, X, Workflow, Lightbulb, Rocket, Translate, BookOpen, Code} from 'lucide-react';

const Icons = {
  arrowRight: ArrowRight,
  check: Check,
  chevronDown: ChevronsUpDown,
  circle: Circle,
  workflow: Workflow,
  close: X,
  copy: Copy,
  dark: Moon,
  edit: Edit,
  externalLink: ExternalLink,
  file: File,
  help: HelpCircle,
  home: Home,
  light: Sun,
  loader: Loader2,
  mail: Mail,
  messageSquare: MessageSquare,
  plus: Plus,
  plusCircle: PlusCircle,
  search: Search,
  server: Server,
  settings: Settings,
  share: Share2,
  shield: Shield,
  shieldCheck: ShieldCheck,
  spinner: Loader2,
  trash: Trash,
  user: User,
  panelLeft: PanelLeft,
  lightbulb: Lightbulb,
  rocket: Rocket,
  translate: Translate,
  bookOpen: BookOpen,
  code: Code,
};

export {Icons};
